joshhunt/destinySets

- src/views/sets.js
> swap Retro-Grade TG2 and Kerak Type 2 in titan class armor list

- src/views/sets-coo.js
- src/views/sets.js
This should add all the new CoO weapons to their sets. 
There was some guesswork here and there but should be correct.
>  Updating sets with declassified CoO Weapons

- src/setData/dlc1.js
* Added missing Crimson Days shader
* Added Crimson days weapon ornaments
> Crimson Days

- src/setData/dlc1.js
Remove the Crimson Days shaders that didn't drop during the event.
> Crimson shader fix

- src/setData/dlc1.js
> Adding missing Dawning armour pieces

- src/setData/baseGame.js
- src/setData/dlc1.js
* Added appropriate emblems to all sections of base game. - There are still some emblems not represented that don't fit into any of these categories that may need some new sections added.
* Added class specific swords
> Base game emblems

- src/setData/dlc1.js
Added the Eater of Worlds Emblem and merged the Ghost into a 'Extras' section
> Eater of Worlds Emblem & Raid Ghost Merge + Mercury Emblems

- src/setData/baseGame.js
Adds the destination emblem variants to their respective groups on the base game page
> Destination Emblem Variants

- src/setData/dlc1.js
Adds shaders to their appropriate loot tables within the Curse of Osiris Tab
> Add Shaders to CoO Tab

- src/setData/baseGame.js
Added shaders to base game page groups where appropriate
> Added Shaders to Base Game groups

- src/setData/dlc2.js
Finished off the Vanguard & Crucible sets. Also done as much as I know of the Mars Gear. 
Only been to Mars on my Warlock so using the Data Explorer I saw the other gear sets, so hopefully they're correct! Will do Eververse later, minus the emotes as I think that has changed right?
> Completed Vanguard, Crucible & Mars Gear

- src/setData/dlc2.js
Still missing the Ghost, Ship & Sparrow for Escalation Protocol - not too sure on which ones they are yet.
> Escalation Protocol

- src/setData/dlc2.js
Added the emblem I forgot to add.
> Missing Escalation Protocol Emblem

- src/setData/dlc2.js
Only added items that are shown on This Week at Bungie. Will add any missing once Iron Banner is live next week 👍
> Iron Banner Season 3 Gear

- src/setData/dlc2.js
Tried to merge this with my last Pull Request after I submitted but didn't work, sorry for a second one haha
> Iron Banner S3 Exotic Emote

- .flowconfig
- package.json
- src/setData/__tests__/checkSyntax.js
- src/setData/allItems.js
- src/setData/allItemsDeluxe.js
- src/setData/allSeasons.js
- src/setData/baseGame.js
- src/setData/common.js
- src/setData/dlc1.js
- src/setData/dlc2.js
- src/setData/index.js
- src/setData/strikeGear.js
- src/types.js
- tests/setData.js
- yarn.lock
- Create a common.js file to contain item sets that are shared across multiple pages. The purpose of this is to help out with All Seasons
- Add flow types to ensure that set files are (more) correct
- Switch from ava to jest for tests because it comes with create-react-app
> Clean up All Seasons + add IB S3

- src/setData/dlc2.js
Just added the gear visible in the Destiny app.
> Faction Rally S3 Gear

- src/setData/common/factions.js
Added the Winner's Offerings as shown in TWAB
> More Faction S3 Weapons

- src/setData/allSeasons.js
- src/setData/dlc2.js
Source: https://www.youtube.com/watch?v=X-MjnY4l7Iw
Seems like there should be more in the list, but these are the ones I know about so far.
> Added known weapons from Gunsmith Arsenal, Warmind

- src/setData/allSeasons.js
Fills out the Eververse section a little more on the All Seasons screen.
> Add missing Eververse sections for All Seasons

- src/setData/allSeasons.js
- src/setData/dlc1.js
- src/setData/dlc2.js
Hopefully the Ornament Hashes have stayed the same! 👍
> Moved Ornaments, Added Prestige EoW & Solstice of Heroes Items

- src/setData/dlc2.js
Will add more items if they become available :)
> Match Solstice Engram

- src/setData/common/index.js
Not major but I put them round the wrong way haha
> Fixed Order of Emblems

- src/setData/common/index.js
- src/setData/yearOne.js
Just merged sections inside of sets and added more Season numbers. 👍
> Tidy Up - Nothing Deleted, Just Sorted

- src/setData/yearOne.js
Last thing I can see missing out of all the sets, not sure how this one was missing all along haha.
> Missing Emblem

- src/setData/yearTwo.js
- Last Wish Section Update
- Iron Banner Shader
- Gambit Shotgun Added - Regarding - https://github.com/joshhunt/destinySets/issues/159
- Section Names Updated to Match Year 1 Page
- Eververse Update
🙂
> Forsaken Page Update

- src/setData/yearTwo.js
Don't know how I put it in twice, saw it today when I used the Collected Items filter.
> Removed Duplicate Ghost Shell

- src/setData/yearTwo.js
This adds the Secret Victories ascendant challenge emblem to the Dreaming City extras.
> Added 'Secret Victories' emblem for Dreaming City

- src/setData/yearOne.js
- src/setData/yearTwo.js
Mainly fixing the duplicate Dawning items - in-case the event comes back. Only kept/added the hashes that are tracked in collections.
> Few Updates

- src/setData/strikeGear.js
Just for the sake of completionists everywhere.
> Adding emblem variants to Forsaken Strike gear

- src/setData/yearTwo.js
Only what's visible in the Vendor Inventory 👍
> Season 5 - Vanguard, Crucible & Gambit

- src/setData/yearTwo.js
Feel free to format/beautify this file when you make next a change. I used the GitHub online editor for this haha
> Season 5 - Iron Banner, Crucible, Vanguard, Forge Ghosts, Raid Emblem

- src/views/App/index.js
Resolves - https://github.com/joshhunt/destinySets/issues/201
> Resolves Issue 201

- src/setData/yearTwo.js
Only the start, will look into the new Reckoning Armour and Eververse later 👍
> Start of Season 6 

- src/setData/yearTwo.js
Eververse & First Set of new Reckoning Armour 👍
> Season 6 - Push 2

- src/setData/yearTwo.js
Alright, this is my last one for the day. There's a lot of Armour by the looks of it & this is only Tier 1!
> Illicit Armour

- src/setData/yearTwo.js
Just a few more items ready for next week 🙂
> Revelry Prep

- src/setData/yearTwo.js
Resolves https://github.com/joshhunt/destinySets/issues/213
Oops lol
> Wrong Titan Ornament

- src/setData/yearTwo.js
> Shader, Sparrow

- src/setData/yearTwo.js
Not sure if/when this ship will be available so just hiding it for the time being! 🙂
> Hide Season 6 Iron Banner Ship

- src/setData/common/index.js
- src/setData/yearTwo.js
> Solstice of Heroes

- src/setData/common/index.js
> Fix EV-37 Voidstreak

- src/setData/yearThree.js
JpDeathBlade collected all the hashes. Just showing all items **planned*** items to be sold for Bright Dust 🙂
If being sold for Silver, they'll still show as purchasable. Haven't had chance to look into that yet - too busy grinding 😅
> Season 8 Eververse

- src/setData/yearOne.js
- src/setData/yearThree.js
- src/setData/yearTwo.js
- Added Ghost now Available
- Finished Raid Set
- Fixed a comment from Year 1
🙂
> Eververse Loot 8th October

- src/setData/yearThree.js
- src/setData/yearTwo.js
> Season Pass, Festival of the Lost (Start) & Eververse S8 Week 3

- src/lib/i18n.js
> Implement Simplified Chinese support

- src/setData/yearThree.js
Thanks to https://twitter.com/JpDeathBlade for Eververse + Dawning Lists!
Closes #263
> S9 Eververse

- src/setData/yearThree.js
- src/setData/yearTwo.js
- Adding a previous **Silver Exclusive** item, that's now being sold for Bright Dust 😡
- Sorted out Obilisk Link Weapons
> Season 9 Week 2

- src/setData/yearThree.js
- Guardian Games items
- Trials items re-order
- Eververse Season 10
- Eververse Stock Season 10 Week 1
> Finish of Season 10?

- src/extraData/catalystTriumphs.js
> New Catalysts

- src/extraData/catalystTriumphs.js
- src/setData/yearThree.js
^ Title + Tommy's Matchbook Catalyst
> Eververse S10W5

- scripts/createModsData.js
- src/setData/modsGenerated.js
- src/setData/strikeGear.js
- Can leave this until they're in collections, otherwise it seems they'll show as collected.
- Sorted some strike loot to match collections.
> Season 11 Mods

- src/setData/yearThree.js
Will leave this here and add any extra items from FoTL next week! 👍
> Finish Festival of the Lost

- src/setData/catalysts.js
- src/setData/yearOne.js
- src/setData/yearThree.js
- src/setData/yearTwo.js
- Hide Festival of the Lost shader that wasn't in-game
- Renamed Catalyst Category
- Sorted pages
- Added Whisper & Outbreak
> Hide & Sort

- src/components/ExtraInfo/index.js
- src/components/Item/index.js
- src/components/Item/styles.styl
- src/components/ItemModal/index.js
- src/components/ItemTooltip/index.js
- src/components/Objectives/index.js
- src/components/Objectives/styles.styl
- src/lib/getItemExtraInfo.js
- src/views/Inventory/index.js
- src/views/SolsticeOfHeroes/index.js
- No loot changes
- Modal/Tooltip changes
- Solstice page improvements (if it returns again)
- Fix available at vendor text, if the item has no cost
- Hide Solstice promo
> S14W10 -> S14W13
