joshhunt/destinySets

src/setData/dlc1.js
- Replace Mercury Treasure Seeker with Fields of Glass
- Add missing Prophetic Arsenal
- Split public space emblems from achievement emblems
- Add Sonic Simulation to promotional section despite it being classified
=> Mercury destination emblem

src/setData/dlc1.js
Add the "normal" Trials ornaments as they have different unlock requirements than the Prestige ornaments; namely prestige ornaments requires flawless runs and increased number of kills.
=> Add normal Trials ornaments; differentiate from flawless ornaments

src/setData/dlc2.js
Reverts joshhunt/destinySets#109
Bungie confirmed it's only available from Eververse and not tied to Iron Banner. 
https://www.reddit.com/r/DestinyTheGame/comments/8lcd9o/thank_you_for_letting_me_do_a_direct_purchase_of/dzel5ef/
=> Revert "Iron Banner S3 Exotic Emote"

src/lib/i18n.js
Added support for the Korean manifest. This is in response to issue #150 
I also noticed that changing languages requires a manual refresh before it tries to load the new manifest. I did not address that in this pull request but I'll make an issue.
=> Korean Localization

src/lib/definitions/index.js, src/store/preloadStore.js, src/views/Inventory/index.js
There is a memory issue, but it will force a refresh if the error occurs. This fixes the issue, but is obviously an unoptimal solution.
There is code copy pasted from preloadStore into inventory. A better solution would be to have a single function both could use, but I was unable to get one working.
There is probably a better way to do everything I've done here, but this fixes the primary problem in #152 where it just does nothing.
=> Added language loading on language change.

src/lib/destinyEnums.js, src/lib/fancySearch.js, src/lib/sortItemsIntoSections.js, src/setData/allItems.js, src/setData/yearTwo.js
This adds the new ghost projection mods from Eververse. The items have been added to yearTwo as a list and a searchable category and grouping added to the libraries. For the all items page there wasn't really a great place to slot these in so I created a new ghosts section and merged the existing ghost on the page into it. This seems consistent with how sparrows and ships are handled but I kept them under the gear category.
Note: None of these changes are tested, I looked over the code and duplicated other similar items as close as possible so I think it should be good. Tried to get the code to run but I believe with the addition of the fontawesome-pro libraries it's impossible to run now without a license to that?
=> Add Ghost Projections

src/extraData/consoleExclusives.js
List of year two exclusives taken from [PlayStation Blog][blog]. Removed all year one exclusives as they should all be available now on Xbox/PC as per this [Activision post][activision].
Fixes #164.
[blog]: https://blog.us.playstation.com/2018/08/30/destiny-2-forsaken-playstation-exclusive-content-detailed/
[activision]: https://blog.activision.com/t5/Destiny/Announcing-Forsaken-The-First-Major-Expansion-For-Destiny-2/ba-p/10745557
=> Update PlayStation exclusives list

src/components/CTA/index.js, src/components/CTA/styles.styl, src/components/Dismissable/index.js, src/components/Header/index.js, src/components/Header/styles.styl, src/components/LoginCTA/index.js, src/components/LoginUpsell/index.js, src/components/LoginUpsell/styles.styl, src/views/App/index.js
Allow the Login Upsell panel to be dismissable, and return 3 days later (handled via cookie).
I feel that a permanent, persistent panel consuming 27% of the screen height (on a Pixel 2) is a bad UX pattern. Allowing the panel to be dismissed should allow the user to see more content, and reduce potential friction.
* Made the Login Upsell component dismissable
* Added `onDismissed` callback to the `Dismissable` component
* Create a cookie "dismissed_login_upsell" with `max-age` of 3 days after dismissing Login Upsell
* This cookie is only checked once, on App mount
* The existence of this cookie hides the Login Upsell component
* Added a new Login CTA to the desktop header
* Added a new Login CTA to the mobile sidebar
=> Update Login Call to Action

src/views/Triumphs/index.js
link prefix was being created by joining breadcrumb objects resulting in [object Object]/[object Object] string. Fixed by mapping breadcrumbs to the breadcrumb id. Fix for #172
=> Use breadcrumb ids for link prefix - Fixes #172

src/setData/yearTwo.js
- Added the missing Eververse Season 5 Ghost, wasn't in the Engram Preview
- Le Monarque & Stryker's Sure-Hand
- Specific Forge Shaders
=> S5 Ghost, Forge Shaders & Weapons

src/views/ItemPage/index.js
=> Map socket's plugHash to an array of reusablePlugs for sockets on items that do not have reusablePlugs (curated rolls)

src/setData/yearTwo.js
I looked into adding my request from issue #149 
This is just the ornaments from Season 4 and Season 5 in Eververse. Does not include the event Ornaments. I wasn't sure on the format you might want them displayed, I just wanted to give an example of what I thought should be view-able outside of the "All Items" page.
=> Added S4 and S5 Ornaments to Eververse Section on Forsaken Tab

src/setData/yearTwo.js
Have now gone through the entire list @ [https://destiny.plumbing/en/diff/DestinyInventoryItemDefinition/diff.html](https://destiny.plumbing/en/diff/DestinyInventoryItemDefinition/diff.html)
Added all the items linked to The Revelry (so far), there's some more in there but aren't linked to anything just yet. Don't want to make false assumptions. Will probably be linked in future manifest updates.
Also added the Iron Banner Ship.
Haven't added the rest of The Reckoning armour sets, as I'm not 100% sure how the system works (whether you keep the Tier 1 armour or does it replace it .etc). There's Tier 2 & 3 sets of armour! I think Tier 2 is tomorrow so I guess we'll see! 👍
=> The Revelry & IB Ship

src/setData/yearTwo.js
Hiding one Reckoning Set, hides them all. I'm hoping this will fix it by changing the IDs?
=> Hide Reckoning Set Fix?

src/views/Inventory/selectors.js
Can probably handle this better by ignoring all itemCategoryHash `Dummies`
https://data.destinysets.com/i/InventoryItem:2146650065/ItemCategory:3109687656
Closes #223
=> Blacklist based off of itemCategoryHashes

config-overrides.js
uses either type of slash. voila destinysets boots in windows :tada:
=> windows path support in loader

src/setData/yearTwo.js
Closes https://github.com/joshhunt/destinySets/issues/232
- Adding the missing items. Hiding items only sold for Silver this Season. 
- Sorted order of items to try and match in-game (if an order is available to see in-game)
Can be easily added back, as they're just commented out at the moment, if they're sold for Bright Dust in a future season 🙂
=> Hiding Items only Sold for Silver

src/AppRouter.js, src/components/Header/index.js, src/extraData/consoleExclusives.js, src/setData/baseGame.js, src/setData/dlc2.js, src/setData/index.js, src/setData/strikeGear.js, src/setData/yearOne.js, src/setData/yearThree.js, src/setData/yearTwo.js, src/views/Inventory/selectors.js
- Commented out PS4 Exclusives
- Shadowkeep Items
- Season 8 Items
- Started Eververse, only put the items up for Bright Dust currently.
Might be items missing, but it's a start. Tried adding "K", (Shadowkeep for short (SK)) as a season number, ran fine perfectly locally but threw up errors here. Just wanted to show the difference between Seasonal & Shadowkeep content. Maybe if number, show "Season #", if text parsed show "Text". Probably easier said than done.
Now back to playing 🙂
=> Shadowkeep + Season 8

src/setData/yearThree.js
I think this is the correct item hash for the Braytech Werewolf? I think the other one is like a psuedo-item that a vendor sells, that will then drop this item. I think.
=> Fix Braytech Werewolf

src/setData/yearThree.js, src/setData/yearTwo.js
- Hide Skull of Dire Ahamkara Ornament until Bungie fixes issue of it not appearing for Bright Dust
- Added `The Shattered Throne` Dungeon to Dreaming City
- Re-ordered The Moon items
- Added another Crimson Days Sparrow
=> `The Shattered Throne`, The Moon, Crimson Days & Eververse

src/setData/yearThree.js
Should make it easier to check if someone (me) is missing something from the engram drops. I didn't do the Shaders or Transmats because:
1. It's a lot
2. I'm not confident it limits itself to those.
Did my best to emulate the configuration file, may have gotten somethings wrong.
=> Adding Mnemonic Engram (Season 11) definitions
